#ifndef CONFIG_HPP
#define CONFIG_HPP

#define ATTACK_FRAMES 10
#define PLAYER_MAX_HEALTH 100
#define ATTACK_RANGE 60
#define ATTACK_RANGE_LEFT 2
#define SLASHWAVE_RANGE 20
#define ATTACK_HORIZONTAL_OFFSET 40
#define POST_ATTACK_INVINCIBILITY_DURATION 0
#define DOWNSTAB_INVINCIBILITY_DURATION 180

#define TITLE_SCREEN_STATE 0
#define PLAYING_STATE 1
#define TUNNEL_STATE 2
#define LEVEL2_STATE 3
#define CREDITS_STATE 4
#define CONTROLS_STATE 5
#define CAVE_STATE 6

#define SCREEN_W 1000
#define SCREEN_H 600

#define GROUND_Y 25
#define SPEED 6
#define JUMP_V 18
#define GRAVITY 1
#define LEVEL2_GROUND_Y 2
#define LEVEL2_PIT_X_START 4012
#define LEVEL2_PIT_X_END 4210
#define LEVEL2_RAISED_GROUND_X 4210
#define LEVEL2_RAISED_GROUND_Y 150

#define CAVE_ENTRY_X 710
#define CAVE_ENTRY_Y 600
#define CAVE_LAND_X 710
#define CAVE_LAND_Y 10
#define CAVE_GROUND_Y 10

#define DASH_SPEED 6
#define EVADE_SPEED 10
#define DOWNSTAB_VELOCITY -25

#define PLAYER_MAX_HEALTH 100
#define PLAYER_MAX_STAMINA 100
#define BUG_MAX_HEALTH 100
#define SENTRY_MAX_HEALTH 200

#define DAMAGE_PLAYER_TAKES 20
#define DAMAGE_DEALT_NORMAL 20
#define DAMAGE_DEALT_HEAVY 35

#define STAMINA_COST_DASH 20
#define STAMINA_COST_DOWNSTAB 20
#define STAMINA_REGEN_RATE 1
#define STAMINA_REGEN_INTERVAL 20

#define UI_BAR_X 20
#define UI_BAR_Y 490
#define UI_BAR_WIDTH 250
#define UI_BAR_HEIGHT 100
#define UI_BAR_SPACING 50

#define IDLE_FRAMES 8
#define WALK_FRAMES 7
#define TURN_FRAMES 1
#define JUMP_LEFT_FRAMES 8
#define JUMP_RIGHT_FRAMES 8
#define FALL_LEFT_FRAMES 7
#define FALL_RIGHT_FRAMES 7
#define LAND_FRAMES 7

#define DASH_LEFT_FRAMES 5
#define DASH_RIGHT_FRAMES 5
#define DOWNSTAB_ANTICIPATE_FRAMES 6
#define DOWNSTAB_SLAM_FRAMES 5
#define DOWNSTAB_LAND_FRAMES 7

#define OVERHEAD_ATTACK_RECOVER_FRAMES 2
#define OVERHEAD_ATTACK_SLASHING_FRAMES 7
#define OVERHEAD_ATTACK_SLASHWAVE_FRAMES 3

#define EVADE_LEFT_PRE_FRAMES 2
#define EVADE_LEFT_ACTIVE_FRAMES 4
#define EVADE_LEFT_RECOVER_FRAMES 1
#define EVADE_RIGHT_PRE_FRAMES 2
#define EVADE_RIGHT_ACTIVE_FRAMES 4
#define EVADE_RIGHT_RECOVER_FRAMES 1

#define DEATH_FRAMES 16
#define WAKE_FRAMES_PART1 3
#define WAKE_FRAMES_PART2 3
#define WAKE_FRAMES_PART3 3
#define ROAR_FRAMES 4
#define ROAR_ACTIVE_FRAMES 2
#define ROAR_END_FRAMES 1
#define INTRO_ANIMATION_SPEED 15
#define DEATH_ANIMATION_DURATION 100

#define SPRITE_SIZE 512
#define SCALE 0.25

#define BG_SCROLL_SPEED 2
#define BG_WIDTH 1000
#define BG_HEIGHT 600
#define BG_SEGMENTS 5
#define TOTAL_BG_WIDTH (BG_WIDTH * BG_SEGMENTS)

#define MAX_TILES 100
#define TILE_WIDTH 128
#define TILE_HEIGHT 64
#define TILE_SCALE_FACTOR 1.5
#define JUMP_DOWN_VELOCITY -15
#define TILES_PER_ROW 2
#define TILE_ROWS_ABOVE 2
#define TILE_ROWS_BELOW 2
#define TILE_SPACING_X 150
#define TILE_SPACING_Y 100
#define TUNNEL_HOLE_X 4930
#define TUNNEL_HOLE_Y GROUND_Y

#define CAMERA_FOLLOW_SPEED 0.1
#define CAMERA_EDGE_MARGIN 200

#define MAX_CREATURES 3
#define CREATURE_NORMAL_FRAMES 5
#define CREATURE_FLYL_FRAMES 6
#define CREATURE_FLYR_FRAMES 5
#define CREATURE_TURN_FRAMES 2
#define CREATURE_ATTACK_FRAMES 3
#define CREATURE_BURST_FRAMES 5
#define CREATURE_DAMAGE_FRAMES 3
#define CREATURE_SPEED 2
#define CREATURE_ATTACK_SPEED 4
#define CREATURE_ATTACK_RANGE 150
#define CREATURE_DETECTION_RANGE 300
#define CREATURE_SPAWN_TRIGGER 400
#define CREATURE_SIZE 64
#define CREATURE_PATROL_DISTANCE 120
#define SPAWN_POINT_1_X 800
#define SPAWN_POINT_2_X 2500
#define SPAWN_POINT_3_X 4500
#define SPAWN_POINT_Y GROUND_Y

#define SENTRY_IDLE_FRAMES 5
#define SENTRY_WALKL_FRAMES 8
#define SENTRY_WALKR_FRAMES 8
#define SENTRY_RUNL_FRAMES 8
#define SENTRY_RUNR_FRAMES 8
#define SENTRY_ATTACKL_FRAMES 12
#define SENTRY_ATTACKR_FRAMES 12
#define SENTRY_SLASHL_FRAMES 4
#define SENTRY_SLASHR_FRAMES 4
#define SENTRY_TURNL_FRAMES 2
#define SENTRY_TURNR_FRAMES 2
#define SENTRY_WAKE_FRAMES 7
#define SENTRY_DEATH_FRAMES 3
#define SENTRY_DEATHAIR_FRAMES 2
#define SENTRY_DAMAGE_FRAMES 3
#define SENTRY_SIZE 128
#define SENTRY_SPEED 2
#define SENTRY_ATTACK_SPEED 4
#define SENTRY_ATTACK_RANGE 150
#define SENTRY_DETECTION_RANGE 250
#define SENTRY_PATROL_DISTANCE 120
#define SENTRY_MAX_CHASE_DIST 250
#define SENTRY_RUN_SPEED 5
#define SENTRY_JUMP_V 18
#define SENTRY_IDLE_CHANCE 20
#define SENTRY_ATTACK_JUMP_CHANCE 40
#define MAX_SENTRIES 3
#define SENTRY_SPAWN_1_X 800
#define SENTRY_SPAWN_2_X 2500
#define SENTRY_SPAWN_3_X 4000

#define SPARKLE_FRAMES 8
#define MAX_SPARKLES 5

#define TITLE_SKY_FRAMES 27
#define TITLE_FIRE_FRAMES 27
#define TITLE_TRANSITION_FRAMES 2
#define TITLE_ANIMATION_SPEED 8

#define INVENTORY_W 150
#define INVENTORY_H 300
#define INVENTORY_X -10
#define INVENTORY_Y 215

#define PICKUP_SIZE 48
#define PICKUP_DROP_CHANCE 60
#define MAX_PICKUPS 10

#define POTION_DURATION 500
#define POTION_DAMAGE_MULTIPLIER 2

#define POWER_DAMAGE_PERCENT 20
#define GLOW_FRAMES 5
#define GLOW_SIZE 48
#define GLOW_SPEED 10

#define HEART_DURATION 500
#define HEART_REGEN_INTERVAL 150
#define HEART_REGEN_AMOUNT 20

#define GAIN_DURATION 600
#define GAIN_REGEN_INTERVAL 180
#define GAIN_REGEN_AMOUNT 20

#endif
